version: '3.8'

services:
  holo-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Model is baked into the image at /app/model_cache
      # These environment variables are set in the Dockerfile
      # - TRANSFORMERS_CACHE=/app/model_cache
      # - HF_HOME=/app/model_cache

      # Optional: Add Hugging Face token for gated models
      # - HF_TOKEN=${HF_TOKEN}
    # NOTE: No volumes needed! Model is included in the image.
    # Image size is ~16-18GB but startup is instant.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Reduced since model loads instantly
