version: '3.8'

services:
  holo-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Model cache directory - persists model between restarts
      - TRANSFORMERS_CACHE=/app/cache
      - HF_HOME=/app/cache
      # Optional: Add Hugging Face token for gated models
      # - HF_TOKEN=${HF_TOKEN}
    volumes:
      # Named volume for model cache persistence
      # Model downloads once (~14GB) and persists across container restarts
      - model-cache:/app/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  # Persistent volume for model cache
  # To reset: docker-compose down -v (removes volume)
  # To inspect: docker volume inspect holo-fastapi-service_model-cache
  model-cache:
